services:
  - type: web
    name: restaurant-sans-site-web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
